"""SQLAlchemy models for Reddit Analyzer."""

from sqlalchemy import (
    Column, Integer, String, Text, TIMESTAMP,
    Enum, DECIMAL, JSON, BigInteger, ForeignKey
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from .connection import Base


class RedditPost(Base):
    """
    Metadata for Reddit posts.
    Avoids re-fetching from Reddit API.
    """
    __tablename__ = 'reddit_posts'

    id = Column(String(20), primary_key=True, comment='Reddit post ID')
    subreddit = Column(String(100), nullable=False, index=True)
    title = Column(Text, nullable=False)
    author = Column(String(100))
    score = Column(Integer)
    num_comments = Column(Integer)
    created_utc = Column(BigInteger, index=True, comment='Unix timestamp')
    url = Column(Text)
    selftext = Column(Text, comment='Truncated to 1000 chars')
    fetched_at = Column(TIMESTAMP, server_default=func.now())

    # Relationship
    classification = relationship(
        "Classification",
        back_populates="post",
        uselist=False,  # One-to-one
        cascade="all, delete-orphan"
    )

    def to_dict(self):
        """Convert model to dict."""
        return {
            'id': self.id,
            'subreddit': self.subreddit,
            'title': self.title,
            'author': self.author,
            'score': self.score,
            'num_comments': self.num_comments,
            'created_utc': self.created_utc,
            'url': self.url,
            'selftext': self.selftext
        }


class Classification(Base):
    """
    Classifications generated by Claude.
    One classification per post (UNIQUE KEY).
    """
    __tablename__ = 'classifications'

    id = Column(Integer, primary_key=True, autoincrement=True)
    post_id = Column(
        String(20),
        ForeignKey('reddit_posts.id', ondelete='CASCADE'),
        nullable=False,
        unique=True
    )
    category = Column(
        Enum(
            'technical', 'troubleshooting', 'research_verified',
            'mystical', 'unverified_claim', 'engagement_bait',
            'community', 'meme', 'outlier',
            name='category_enum'
        ),
        nullable=False,
        index=True
    )
    confidence = Column(DECIMAL(3, 2), comment='0.00-1.00')
    red_flags = Column(JSON, comment='Array of red flags')
    reasoning = Column(Text)
    model_version = Column(String(50), default='claude-haiku-4-5-20251001')
    classified_at = Column(TIMESTAMP, server_default=func.now(), index=True)

    # Relationship
    post = relationship("RedditPost", back_populates="classification")

    def to_dict(self):
        """Convert model to dict."""
        return {
            'post_id': self.post_id,
            'category': self.category,
            'confidence': float(self.confidence) if self.confidence else None,
            'red_flags': self.red_flags or [],
            'reasoning': self.reasoning,
            'model_version': self.model_version
        }


class ScanHistory(Base):
    """
    Scan history for tracking and analytics.
    """
    __tablename__ = 'scan_history'

    id = Column(Integer, primary_key=True, autoincrement=True)
    subreddit = Column(String(100), nullable=False, index=True)
    scan_date = Column(TIMESTAMP, server_default=func.now(), index=True)
    posts_fetched = Column(Integer, comment='Total posts from Reddit')
    posts_classified = Column(Integer, comment='New posts classified')
    posts_cached = Column(Integer, comment='Posts from cache')
    signal_ratio = Column(DECIMAL(5, 2), comment='Signal percentage')

    def to_dict(self):
        """Convert model to dict."""
        return {
            'subreddit': self.subreddit,
            'scan_date': self.scan_date,
            'posts_fetched': self.posts_fetched,
            'posts_classified': self.posts_classified,
            'posts_cached': self.posts_cached,
            'signal_ratio': float(self.signal_ratio) if self.signal_ratio else None
        }
